import cssText from "../styles.css?inline";
import type { AppState } from "../context/AppReducer";
import type { Violation } from "../types";
import { activeViolations, displayCategory } from "./filters";
import { LINT_CATEGORIES } from "../constants";
import { excludedView } from "./exclusions";
import { answeredManualChecks } from "./manualChecks";

function projectName(state: AppState): string {
  const wd = (state.meta.workingDirectory ?? "").replace(/[\\/]+$/, "");
  const seg = wd.split(/[\\/]/).filter(Boolean);
  return seg.length ? seg[seg.length - 1]! : "Mendix project";
}

export function buildReportHtml(state: AppState): string {
  const reportViolations = activeViolations(state);
  const ev = excludedView(state);
  const answered = answeredManualChecks(state.manualAnswers);
  const exNote = ev.matchedCount ? ` · ${ev.matchedCount} excluded` : "";
  const now = new Date().toLocaleString("en-GB");
  const proj = projectName(state);

  const categoryRows = LINT_CATEGORIES.map((c) => {
    const count = reportViolations.filter((v) => displayCategory(v, state.ruleCategories) === c).length;
    return `<div class="lint-countrow"><span class="label">${c}</span><span class="count">${count}</span></div>`;
  }).join("\n");

  const catHtml = `<div class="lint-card"><h3>Improvements per category</h3>${categoryRows}<div class="lint-countrow lint-total"><span class="label">Total</span><span class="count">${reportViolations.length}</span></div></div>`;

  const logoHtml = state.logoDataUri
    ? `<img class="lint-logo" src="${state.logoDataUri}" alt="CLEVR" />`
    : "";

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>CLEVR Lint Review — ${proj}</title>
<style>
${cssText}
body { margin: 16px; max-width: 1200px; }
</style>
</head>
<body>
<div class="lint-root">
<div class="lint-header">
  <div class="lint-brand">
    ${logoHtml}
    <div>
      <h1 class="lint-title">CLEVR Lint Review</h1>
      <div class="lint-subtitle">${proj} · ${reportViolations.length} improvements${exNote} · generated ${now}</div>
    </div>
  </div>
</div>
<div class="lint-summary lint-summary-3">${catHtml}</div>
${LINT_CATEGORIES.map((c) => {
  const items = reportViolations.filter((v) => displayCategory(v, state.ruleCategories) === c);
  if (!items.length) return "";
  return buildCategoryHtml(c, items, state);
}).join("\n")}
${buildExcludedHtml(state)}
${buildAnsweredHtml(answered)}
<div class="lint-footer">Generated by CLEVR Lint · requires Mendix Studio Pro 11 or higher · ${now}</div>
</div>
</body>
</html>`;
}

function esc(s: string | undefined): string {
  return (s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function buildCategoryHtml(category: string, items: Violation[], state: AppState): string {
  const byRule = new Map<string, { rule: Violation; vs: Violation[] }>();
  for (const v of items) {
    if (!byRule.has(v.ruleId)) byRule.set(v.ruleId, { rule: v, vs: [] });
    byRule.get(v.ruleId)!.vs.push(v);
  }
  const rules = [...byRule.values()].sort((a, b) => {
    const ak = a.rule.kind === "lint" ? 0 : 1;
    const bk = b.rule.kind === "lint" ? 0 : 1;
    return ak - bk || a.rule.ruleId.localeCompare(b.rule.ruleId);
  });

  const rulesHtml = rules.map(({ rule, vs }) => {
    const sev = rule.severity ?? "";
    const name = rule.kind === "lint" ? (rule.lintCode ?? "") : (state.ruleNames[rule.ruleId] ?? "");
const instancesHtml = vs.map((v) => {
      const where = v.elementName
        ? `${esc(v.documentType)}: <span class="qname">${esc(v.documentQualifiedName)}</span> › <span class="elem">${esc(v.elementName)}</span>`
        : `${esc(v.documentType)}: <span class="qname">${esc(v.documentQualifiedName)}</span>`;
      return `<div class="lint-instance">
  <div class="lint-doc"><span class="doctype">${where}</span></div>
  <div class="lint-reason">${esc(v.reason)}</div>
  ${v.suggestion ? `<div class="lint-suggestion">${esc(v.suggestion)}</div>` : ""}
  ${v.documentationUrl ? `<div class="lint-docslink"><a href="${esc(v.documentationUrl)}" target="_blank" rel="noreferrer">Documentation</a></div>` : ""}
</div>`;
    }).join("\n");

    return `<details class="lint-rule sevbar-${sev}" open>
  <summary>
    <span class="sev sev-${sev}">${esc(sev)}</span>
<span class="lint-ruleid">${esc(rule.ruleId)}</span>
    ${name ? `<span class="lint-acrcode">${esc(name)}</span>` : ""}
    <span class="lint-rule-count">${vs.length} improvements</span>
  </summary>
  <div class="lint-rule-body">${instancesHtml}</div>
</details>`;
  }).join("\n");

  return `<div class="lint-group">
  <div class="lint-group-head"><h3>${esc(category)}</h3><span class="lint-group-count">${items.length} improvements</span></div>
  ${rulesHtml}
</div>`;
}

function buildExcludedHtml(state: AppState): string {
  const ev = excludedView(state);
  if (!ev.groups.length) return "";
  const groupsHtml = ev.groups.map((g) => {
    const name = state.ruleNames[g.ruleId] ?? "";
    const entriesHtml = g.entries.map((e) => {
      const where = e.exclusion.elementName
        ? `${esc(e.exclusion.documentQualifiedName)} › ${esc(e.exclusion.elementName)}`
        : esc(e.exclusion.documentQualifiedName);
      const meta = [e.exclusion.excludedBy ? `by ${esc(e.exclusion.excludedBy)}` : "", esc(e.exclusion.date)].filter(Boolean).join(" · ");
      return `<div class="lint-excluded-card${e.isStale ? " stale" : ""}">
  <div class="lint-excluded-top">
    <span class="lint-ruleid">${esc(e.exclusion.ruleId)}</span>
    ${where ? `<span class="lint-excluded-where">${where}</span>` : ""}
    ${e.isStale ? '<span class="lint-stale-badge">stale — no longer matches</span>' : ""}
    ${e.violations.length > 1 ? `<span class="lint-excluded-applies">applies to ${e.violations.length} findings</span>` : ""}
  </div>
  <div class="lint-excluded-reason">Reason: ${esc(e.exclusion.reason)}</div>
  ${meta ? `<div class="lint-excluded-meta">${meta}</div>` : ""}
</div>`;
    }).join("\n");
    return `<div class="lint-excluded-rule">
  <div class="lint-excluded-rule-head">
    <span class="lint-ruleid">${esc(g.ruleId)}</span>
    ${name ? `<span class="lint-acrcode">${esc(name)}</span>` : ""}
    <span class="lint-excluded-rule-count">${g.findingCount} excluded${g.staleEntries ? ` · ${g.staleEntries} stale` : ""}</span>
  </div>
  ${entriesHtml}
</div>`;
  }).join("\n");
  return `<div class="lint-excluded">
  <div class="lint-section-head"><h2>Excluded improvements</h2><span class="lint-section-count">${ev.matchedCount} excluded${ev.staleCount ? ` · ${ev.staleCount} stale` : ""}</span></div>
  <div class="lint-section-note">Intentionally not fixed — each with a reason, shared with the team via version control.</div>
  ${groupsHtml}
</div>`;
}

function buildAnsweredHtml(answered: ReturnType<typeof answeredManualChecks>): string {
  if (!answered.length) return "";
  const cardsHtml = answered.map((s) => `<div class="lint-excluded-card">
  <div class="lint-excluded-top">
    <span class="lint-ruleid">${esc(s.def.id)}</span>
    <span class="lint-acrcode">${esc(s.def.category)}</span>
    <span class="lint-excluded-applies">answered "Yes" on ${esc(s.answer?.date)} — recheck due ${esc(s.recheckDate)}</span>
  </div>
  <div class="lint-excluded-reason">${esc(s.def.question)}</div>
  <div class="lint-excluded-meta">Answer: ${esc(s.answer?.note)} — by ${esc(s.answer?.answeredBy ?? "?")}</div>
</div>`).join("\n");
  return `<div class="lint-excluded">
  <div class="lint-section-head"><h2>Answered manual checks</h2><span class="lint-section-count">${answered.length} answered (valid)</span></div>
  <div class="lint-section-note">Consciously assessed — re-checked every 30 days; shared with the team via version control.</div>
  ${cardsHtml}
</div>`;
}
