using System.Diagnostics;
using System.Text;

namespace Clevr.Acr.Extension;

/// <summary>
/// Writes the standalone HTML report generated by the web UI to disk.
/// The UI (render layer) builds the HTML — this is only the writing/opening (IO),
/// so that the data/UI separation remains intact.
///
/// Location: <projectdir>\.clevr-acr\ (consistent with spec section 3), or the temp dir
/// if there is no project directory. Filename with timestamp so that earlier reports
/// are preserved.
/// </summary>
public static class ReportExporter
{
    public static string Write(string html, string? projectDir)
    {
        var baseDir = !string.IsNullOrWhiteSpace(projectDir) && Directory.Exists(projectDir)
            ? Path.Combine(projectDir!, ".clevr-acr")
            : Path.Combine(Path.GetTempPath(), "clevr-acr");

        Directory.CreateDirectory(baseDir);
        var fileName = $"CLEVR-ACR-report-{DateTime.Now:yyyyMMdd-HHmmss-fff}.html";
        var path = Path.Combine(baseDir, fileName);

        File.WriteAllText(path, html, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        return path;
    }

    /// <summary>Opens the report in the default browser. Best-effort: fails silently.</summary>
    public static void TryOpen(string path)
    {
        try
        {
            Process.Start(new ProcessStartInfo { FileName = path, UseShellExecute = true });
        }
        catch
        {
            // Opening is a bonus; the path has already been reported to the user.
        }
    }
}
